
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

target 'JDStatusBarNotificationExample' do
    project 'JDStatusBarNotificationExample'

    pod 'InfColorPicker'
    pod 'FTFontSelector'
end
